<?php

namespace InventarioBundle\Repository;

/**
 * DetalleSalidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleSalidaRepository extends \Doctrine\ORM\EntityRepository
{
}
