<?php

namespace InventarioBundle\Repository;

/**
 * DetalleTraspasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleTraspasoRepository extends \Doctrine\ORM\EntityRepository
{
}
