<?php

namespace InventarioBundle\Repository;

/**
 * DetalleEntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleEntradaRepository extends \Doctrine\ORM\EntityRepository
{
}
