<?php

namespace InventarioBundle\Repository;

/**
 * traspasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class traspasoRepository extends \Doctrine\ORM\EntityRepository
{
}
