<?php

namespace InventarioBundle\Repository;

/**
 * ZapatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZapatoRepository extends \Doctrine\ORM\EntityRepository
{
}
